{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "health-reporter.name" . }}
    chart: {{ include "health-reporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
